/**
 * Image pipeline for the invitation.
 *
 * Reads the untouched photographs in assets/originals/ and writes web-ready
 * derivatives into public/images/: cinematic / portrait / detail crops with a
 * very light warm grade (no retouching of faces), plus a generated manifest
 * (dimensions + blur placeholders) used by next/image, and the Open Graph card.
 *
 *   npm run images
 */
import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import satori from "satori";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const originals = path.join(root, "assets/originals");
const publicDir = path.join(root, "public/images");

/** Every derivative the site uses. Crops are in source-pixel coordinates. */
const derivatives = [
  // ── couple / storytelling ──────────────────────────────────────────
  { id: "couple/rahul-sweta-hero-wide", src: "rahul-sweta-smiling.jpg" },
  {
    id: "couple/rahul-sweta-hero-portrait",
    src: "rahul-sweta-smiling.jpg",
    crop: { left: 600, top: 0, width: 760, height: 1066 },
  },
  { id: "couple/rahul-sweta-together-wide", src: "rahul-sweta-back-to-back.jpg" },
  {
    id: "couple/rahul-sweta-together-mobile",
    src: "rahul-sweta-back-to-back.jpg",
    crop: { left: 440, top: 0, width: 1160, height: 1066 },
  },
  { id: "couple/rahul-sweta-formal", src: "rahul-sweta-formal-standing.jpg" },
  { id: "couple/rahul-sweta-candid", src: "rahul-sweta-candid.jpg" },
  { id: "couple/sweta-portrait", src: "sweta-portrait.jpg" },

  // ── gallery details (editorial crops) ──────────────────────────────
  {
    id: "gallery/detail-hand-on-shoulder",
    src: "rahul-sweta-smiling.jpg",
    crop: { left: 800, top: 380, width: 360, height: 470 },
  },
  {
    id: "gallery/detail-mehndi-clutch",
    src: "sweta-portrait.jpg",
    crop: { left: 330, top: 930, width: 440, height: 670 },
  },
  {
    id: "gallery/detail-sweta-profile",
    src: "rahul-sweta-back-to-back.jpg",
    crop: { left: 1020, top: 240, width: 580, height: 826 },
  },
  {
    id: "gallery/detail-rahul-profile",
    src: "rahul-sweta-back-to-back.jpg",
    crop: { left: 560, top: 60, width: 560, height: 800 },
  },
];

/** A gentle, warm "film" grade — keeps skin tones natural. */
async function grade(input, { width, height }) {
  const warm = await sharp({
    create: { width, height, channels: 4, background: { r: 255, g: 214, b: 170, alpha: 0.1 } },
  })
    .png()
    .toBuffer();

  const vignette = Buffer.from(
    `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <defs><radialGradient id="v" cx="50%" cy="48%" r="75%">
        <stop offset="62%" stop-color="#000" stop-opacity="0"/>
        <stop offset="100%" stop-color="#1a0508" stop-opacity="0.28"/>
      </radialGradient></defs>
      <rect width="100%" height="100%" fill="url(#v)"/>
    </svg>`,
  );

  return sharp(input)
    .modulate({ brightness: 1.01, saturation: 0.95 })
    .linear(1.04, -5)
    .composite([
      { input: warm, blend: "soft-light" },
      { input: vignette, blend: "over" },
    ]);
}

async function build() {
  await fs.mkdir(publicDir, { recursive: true });
  const manifest = {};

  for (const d of derivatives) {
    let pipeline = sharp(path.join(originals, d.src)).rotate();
    if (d.crop) pipeline = pipeline.extract(d.crop);
    const cropped = await pipeline.toBuffer({ resolveWithObject: true });
    const { width, height } = cropped.info;

    const graded = await grade(cropped.data, { width, height });
    const out = path.join(publicDir, `${d.id}.jpg`);
    await fs.mkdir(path.dirname(out), { recursive: true });
    const jpg = await graded.jpeg({ quality: 84, mozjpeg: true, chromaSubsampling: "4:4:4" }).toBuffer();
    await fs.writeFile(out, jpg);

    const blur = await sharp(jpg).resize(16).webp({ quality: 40 }).toBuffer();
    manifest[d.id] = {
      src: `/images/${d.id}.jpg`,
      width,
      height,
      blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    };
    console.log(`✓ ${d.id}  ${width}×${height}  ${(jpg.length / 1024).toFixed(0)} KB`);
  }

  const ts = `// AUTO-GENERATED by scripts/process-images.mjs — do not edit by hand.
export const imageManifest = ${JSON.stringify(manifest, null, 2)} as const;

export type ImageId = keyof typeof imageManifest;
`;
  await fs.writeFile(path.join(root, "src/data/imageManifest.generated.ts"), ts);

  await buildOgImage();
}

/** 1200×630 share card for WhatsApp / social previews. */
async function buildOgImage() {
  const fonts = [
    { name: "Cormorant", data: await fs.readFile(path.join(root, "assets/fonts/cormorant-600.ttf")), weight: 600, style: "normal" },
    { name: "Manrope", data: await fs.readFile(path.join(root, "assets/fonts/manrope-600.ttf")), weight: 600, style: "normal" },
  ];

  const photo = await sharp(path.join(publicDir, "couple/rahul-sweta-hero-wide.jpg"))
    .extract({ left: 520, top: 0, width: 960, height: 1066 })
    .resize(640, 630, { fit: "cover", position: "top" })
    .jpeg({ quality: 88 })
    .toBuffer();
  const photoUri = `data:image/jpeg;base64,${photo.toString("base64")}`;

  const gold = "#d4b06a";
  const el = (type, style, children) => ({ type, props: { style, children } });

  const svg = await satori(
    el("div", { width: 1200, height: 630, display: "flex", background: "#2a0a10", fontFamily: "Manrope" }, [
      el(
        "div",
        {
          width: 560, height: 630, display: "flex", flexDirection: "column", alignItems: "center",
          justifyContent: "center", position: "relative",
          background: "radial-gradient(circle at 50% 40%, #5a1420 0%, #2a0a10 75%)",
        },
        [
          el("div", { position: "absolute", top: 28, left: 28, right: 28, bottom: 28, border: `1.5px solid ${gold}`, display: "flex" }, ""),
          el("div", { position: "absolute", top: 38, left: 38, right: 38, bottom: 38, border: `1px solid rgba(212,176,106,0.35)`, display: "flex" }, ""),
          el("div", { color: gold, fontSize: 18, letterSpacing: 8, marginBottom: 26 }, "THE WEDDING OF"),
          el("div", { color: "#f8f1e6", fontFamily: "Cormorant", fontSize: 84, lineHeight: 1 }, "Dr. Rahul"),
          el("div", { color: gold, fontFamily: "Cormorant", fontSize: 40, margin: "10px 0" }, "weds"),
          el("div", { color: "#f8f1e6", fontFamily: "Cormorant", fontSize: 84, lineHeight: 1 }, "Sweta"),
          el("div", { width: 120, height: 1, background: gold, margin: "30px 0 24px" }, ""),
          el("div", { color: "#ecd9bf", fontSize: 22, letterSpacing: 6 }, "12 DECEMBER 2026"),
          el("div", { color: "rgba(236,217,191,0.7)", fontSize: 15, letterSpacing: 4, marginTop: 12 }, "CHAPRA · BIHAR"),
        ],
      ),
      el("div", { width: 640, height: 630, display: "flex", position: "relative" }, [
        { type: "img", props: { src: photoUri, width: 640, height: 630, style: { objectFit: "cover" } } },
        el("div", { position: "absolute", top: 0, left: 0, width: 90, height: 630, display: "flex", background: "linear-gradient(90deg, #2a0a10, rgba(42,10,16,0))" }, ""),
      ]),
    ]),
    { width: 1200, height: 630, fonts },
  );

  const out = path.join(root, "public/og/rahul-sweta-og.jpg");
  await fs.mkdir(path.dirname(out), { recursive: true });
  await sharp(Buffer.from(svg)).jpeg({ quality: 86, mozjpeg: true }).toFile(out);
  console.log("✓ og/rahul-sweta-og.jpg");
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
