// AUTO-GENERATED by scripts/process-images.mjs — do not edit by hand.
export const imageManifest = {
  "illustrations/rahul-sweta-namaste": {
    "src": "/images/illustrations/rahul-sweta-namaste.jpg",
    "width": 900,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAsAA4BaJZACdAED9jAbaMAA/rf8yAo+Al5PeTBhaGONAb4Ys7O59mgKU+BwmoQYb6jpFIKQ+AXIE6oLW6422Hb3elmXxD7VbhSMNbkTfWE0EAA="
  },
  "illustrations/rahul-sweta-namaste-mobile": {
    "src": "/images/illustrations/rahul-sweta-namaste-mobile.jpg",
    "width": 680,
    "height": 604,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQAgCdASoQAA4AA4BaJYgCdAYyfbWnFMQeLcAA/fooIIeswYuh4KKhURBwUqvOIIH59s3Pb+cMtzSsHouPqRK23Cu/RjSqbuBCxSRSjAbjBkT7cNDNg3O6sFi1djFr1s2DpQrKv8Iu5wAA"
  },
  "illustrations/rahul-sweta-staircase": {
    "src": "/images/illustrations/rahul-sweta-staircase.jpg",
    "width": 1032,
    "height": 1818,
    "blurDataURL": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACQBACdASoQABwAPu1iqk2ppaQiMAgBMB2JYwCdAYzG3sRcuchLF/yjVmr2OAAA/u/CnvcYSfrSUY4PQyMj3rhWKOQgYvnVMEtlHg6JzkBPDw5ib9gHEM+E2xQ6neb4SKhO2Phd5EZV26UeU4o9Xxd31B1glSd5FeVi04oezXDBWxoJ46jDG3ab1OhpVYm4QrobGR+pw2GxgAAA"
  },
  "illustrations/rahul-sweta-embrace": {
    "src": "/images/illustrations/rahul-sweta-embrace.jpg",
    "width": 612,
    "height": 962,
    "blurDataURL": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACwBACdASoQABkAPu1iqU2ppaOiMAgBMB2JYwCdMoBOAbUA1m9/3743KAkn/PKwAP7KfOziDaP8neAcLPeLmYfTznv7vb0z9NDxv+Ce1JvBKkdnMTiNqTzA/qS/pEy3ZdGDRZuwXKTqPOm1Ywn3qL0nG/IbZxOsq4gGeCzqIb6wQglBMMx8BT/bH2TDRVdwDCzoYS5gZ40QvF6+JJY6B3BLp2yaARKvcSIBBWuSZMKcAAAA"
  },
  "illustrations/rahul-sweta-together": {
    "src": "/images/illustrations/rahul-sweta-together.jpg",
    "width": 1241,
    "height": 1897,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOgMZKZNFLX2OZD1c/YAAD+7Vopegbn3imqseX9oGK7wFzxTRXtFWL8PBSoX8e9jyEW7KE0L4D1kC0nt21z7OIvK1tMNcy0kjjcBe358LduH+wzs+K3lq4x2sgI7uutP3uhXTN/l/YJgE/clKQ3ZCqkqdYAAAA="
  },
  "decor/jaimala-couple": {
    "src": "/images/decor/jaimala-couple.webp",
    "width": 479,
    "height": 557,
    "blurDataURL": "data:image/webp;base64,UklGRqQBAABXRUJQVlA4WAoAAAAQAAAADwAAEgAAQUxQSN8AAAABkLpt2/n3wu/ZtrdkJ9teXbNZbUW1JdtWW7LZbP1s3OHzHouICcB7Pfs18G7VX/8DRKG5MgCw899VoP6TJjJVHVqD9BXIbbxqFJNnP3kvI8HMW83xyPN3cgNStV+cMWgu6SInBH7kGdobxshnFUkL+d+gvHKZXFvxALx/kozNbdkmO8vzEfuVJGtD/e/ILchG/qF0yVT/F/lTEfUUfpTXJklXoFZAd1tJOmD8W1Cgt/r/96U70E3hEOKey/eBZIqv4XRj8SiLxFsRbZLO5R41AdWsnvnlxZpErURtl0gAAFZQOCCeAAAA8AMAnQEqEAATAD7tYqlNqaWjojAIATAdiWwAnR/AAgFRAp4gfHbKAADJM2W1z3o/aU7feRn3IblfbZZxVvW/bwKZZ4ihHsHHNT18HZn4/auGlEruJlyOvtlL8yrkisbgBWSUiorYtTq6TVZYW/5dArLB6I/y+pCSv/nHy5ouqeM9hZ/1CqMuQqesRAHjR1T8lcW9P/cw3xg2nZPwgAA="
  },
  "decor/shehnai-couple": {
    "src": "/images/decor/shehnai-couple.webp",
    "width": 565,
    "height": 720,
    "blurDataURL": "data:image/webp;base64,UklGRpIBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSMwAAAABkGPbtqlpp2zbDXBkx7YVsQG2bdtWVKltZrbtqh87eGhDREwAxcgS09GF2M0jTYlIZXtPhY1oPJrSNgEnDtmqJuv/WEOYQ1VLVgGRyNBIDNCH/5c54Zl6RJR4C/Y/zxnELObAvQZD8hzAMYDPM2kikhoAgPpDYHfWlsTTb8HcqQRwkUbp4BwFgGWK5ppjOJDJL9ttD2OMlO7Z8ML4K0VWHAD2Gq6IKngkC3a2k84nj1SBHV9qBM+/0dAh/f88MLnhSQKe1RybQSIS7lJWUDggoAAAAHAEAJ0BKhAAFAA+7WKpTamlo6IwCAEwHYliAKwBiwS57R3yBP6v39TpVoVAAP1z0lX6YR4dJTzNV4y+5mNmGCJHu96KexjP3mu/RUAm89J0QuKMqNs/x/w+s3OV2pgIpUIqwcnn6++uqZlAqEQ633Y9wcPyVsGSRYPVPEdBsw7b16zimenLV+w/ln37goBdrMJ/kt5iiI9yxGiFsFOgAAA="
  },
  "decor/ganesh-mark": {
    "src": "/images/decor/ganesh-mark.webp",
    "width": 514,
    "height": 608,
    "blurDataURL": "data:image/webp;base64,UklGRjgBAABXRUJQVlA4WAoAAAAQAAAADwAAEgAAQUxQSOwAAAABkBxAAAE2F9u2bdu2bdu2bdtvZwCr7pdDdIZohYiYAF7VblDj/aaHz4oCb2mu9scfrkw6vtWjSXVa+3iTxBvxdis1piUDGSFl3i8EDKtFEJKYWxdj9EV3f2wUCvEK/TglASp1KnHBKDqoVtubAui0ZJcq5QiSG9mi4aIFykstAkQbiBYivXlcYuP2s6Kn3cKDWLPS1aSMIY8LM+jpV7S0pOZLzo0jP4XAfkYhHET+y5j+UzryBzJinIBfwkzGWl1JgMSlPYIVowhd6uO16y2A0uTxSYV5+X0FIOAY5WBV3tI72R4lw5uZfNTxHVZQOCAmAAAAsAIAnQEqEAATAD7tYqlNqaWjojAIATAdiWkAAHsgAP7w3y4AAAA="
  },
  "decor/shloka-mark": {
    "src": "/images/decor/shloka-mark.webp",
    "width": 812,
    "height": 158,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4WAoAAAAQAAAADwAAAgAAQUxQSDEAAAAAaCo/RTlDRC1BTlU5R0oUZ4gtT1MsLzszOzwwQTU9GYZjIjY7LEM7OSE7Pz5BOSJiAFZQOCAYAAAAMAEAnQEqEAADAAOAWiWkAANwAP71CAAA"
  }
} as const;

export type ImageId = keyof typeof imageManifest;
