// AUTO-GENERATED by scripts/process-images.mjs — do not edit by hand.
export const imageManifest = {
  "illustrations/rahul-sweta-back-to-back": {
    "src": "/images/illustrations/rahul-sweta-back-to-back.jpg",
    "width": 1024,
    "height": 572,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoQAAkAA4BaJZQCdADwuUnRsAD+9w8/d7SiNVBGe8lis/ylekjXjlYNhomr9SndQ/bmDK+AAAA="
  },
  "illustrations/rahul-sweta-staircase": {
    "src": "/images/illustrations/rahul-sweta-staircase.jpg",
    "width": 1125,
    "height": 2000,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACQBACdASoQAB0APu1mq04ppaQiMAgBMB2JYwC7MoADTrFDqV4whvUbAQNbzYAA/vHPUTa/acei5PwuSFboPpvGNpsfcX6vc3dJ5qT06UJU/wZq29RJDj7D3FSqucEVzT3j/k3VSvIlrCIZ75jWaiOCW++1melH2W+VXXmRUNDgdMte2nHuuEcaCqvhvoKYos8CTqAA"
  },
  "illustrations/sweta-portrait": {
    "src": "/images/illustrations/sweta-portrait.jpg",
    "width": 1332,
    "height": 2000,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYwCdAYvC4Td6u+zuOLJT9u7AAP7v1agSfvcQz4DuR0zKep9tdbZN7tkR8NNJclKms/rNBLh/7FYz2LUA+7xZtstxb69E1D7nXY17ZvFA1WwXivCE7x1w6czm1N3vC6vK5tKzP2a0gYw286F+Rth1nFtzLaCRR1jqDFW6qrkAAA=="
  },
  "illustrations/rahul-sweta-together": {
    "src": "/images/illustrations/rahul-sweta-together.jpg",
    "width": 1332,
    "height": 2000,
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYwCw7B6WvS/QZl3Es6gAAAD+7VJ9Um/sFAoDMpi0k2aXh1Xi+l6gnHficCm6G/8A39M+lBBWLbzJCw3ECAUKDU78AfbBqhTCR153WjIa/as0aKdpfpA7kWEuBeMfoKfzxN89DK1r+QAA"
  }
} as const;

export type ImageId = keyof typeof imageManifest;
