// AUTO-GENERATED by scripts/process-images.mjs — do not edit by hand.
export const imageManifest = {
  "couple/rahul-sweta-hero-wide": {
    "src": "/images/couple/rahul-sweta-hero-wide.jpg",
    "width": 1600,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoQAAsAA4BaJZgCdAEXWVyld/ldYAD+55dYR1yRC2i+O3vmXY+zLb2LpLWetNnqBsSQ5vBokKTS2bA4AhS/Xtz2NmleviXEFQjK8fvxGFtZX9JdGuvEK6YfqG6mBNQAAAA="
  },
  "couple/rahul-sweta-hero-portrait": {
    "src": "/images/couple/rahul-sweta-hero-portrait.jpg",
    "width": 760,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACwBACdASoQABYAPu1iqU2ppaOiMAgBMB2JZgCdMoR8eCTbQX9XWkvh9pxd72wAAPx5KQFX7RppEoGuuh6ZEHBTCKwg/hyKWCFsL4HaW/xhoG9FkXwBwhr4J1ML1dDiqmMXxbLZHtBmFVLpV+bODK1LSd93idPM6UNtgvwBRmuLtmKXvJ3Ubpj8vZIgM1GQMJjPVM8DnJ73FUS9DQJjE66wiKO8gAAA"
  },
  "couple/rahul-sweta-together-wide": {
    "src": "/images/couple/rahul-sweta-together-wide.jpg",
    "width": 1600,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAsAA4BaJZgCdADG8yoEdAD+138CjHn/J6B51QYKz63i26V6VKhQcM6yjqKdaTiQK7cBd4bM7zmNxvbfHi0IEDA1BJBIZdRrUEa6uFlH4dRHzuZA52rXyu3gAA=="
  },
  "couple/rahul-sweta-together-mobile": {
    "src": "/images/couple/rahul-sweta-together-mobile.jpg",
    "width": 1160,
    "height": 1066,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAQCdASoQAA8AA4BaJagCdAEXUpyZYaQAzj/gUpxZ/7kpVjGxn1z7ljpR30Ql2pvuhnvIXq/8Ue6yoRg5VltF6HPRPnADxb5rNKSpppXTejul4XAjg8frGozllPJoo+KEtlJvUTGt7K+oJ/8AAA=="
  },
  "couple/rahul-sweta-formal": {
    "src": "/images/couple/rahul-sweta-formal.jpg",
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZACdAYx2uzOJA7iyS/d9oAD+kLIyFNcMX/v7J/F98TsOLc9J7iJKgDyDlauGE1GzKIMGPjRpNa/81RJiDhc8BOuWU/Akvy/vxbYCLgy1UO6leBRkcXXBOBi5aoRkKaK8MMKcfHhMt/D4mBrsDIbqHjBk9/oWTWhdjR9zVcSKR71E8AAAAA=="
  },
  "couple/rahul-sweta-candid": {
    "src": "/images/couple/rahul-sweta-candid.jpg",
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADwAwCdASoQABgAPu1iqU2ppaQiMAgBMB2JYgCdABk6wHjih1utWDYAAP5p9tVUK2Tj4X6d/p6Hs3x7bPaw3VWLiXGE63q0JJYC8VOnFKOF60UP0VetDllnfSIV5r418rQy0D691Iud2Hq64b8RIh/EZxlyURkYeqnlLQ8PQspv/Kmoc9gAAA=="
  },
  "couple/sweta-portrait": {
    "src": "/images/couple/sweta-portrait.jpg",
    "width": 1066,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYgCw7BRwYbvT/mZeSP42O4AA+Nn3B9qKsZ9GjFTwqnwtPT+LMSIimT2JUwVncz0SKwLOWidWor6OrkFY5apKq/VoTnNgwcXbMIvqf3TemE8TwbCSF5d8nXBRHcVpKaVpyopyC15LjKMqDxT6zYQAAAA="
  },
  "gallery/detail-hand-on-shoulder": {
    "src": "/images/gallery/detail-hand-on-shoulder.jpg",
    "width": 360,
    "height": 470,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JaAC1F1ycfOOduXH/1K/cOL0DxonScAAA/rtLg9O4eZ3tWd+NuV2DuCYr8y1MDNTFETne6WieNDrx/4cqIXs1QE5ds6KKWqy1pqzjDQ30JtcCA+vhW+53LZof/qhJqPp270THdrA+/2uGIMVCFSDdqN6u1WBGFuejHOAA"
  },
  "gallery/detail-mehndi-clutch": {
    "src": "/images/gallery/detail-mehndi-clutch.jpg",
    "width": 440,
    "height": 670,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBYjagAr6+I21v6I8HPFh91wAN3vEHIUjUFh8MVDWWFJwpQZbcCGNA9BcAevW06OAi4RqnLLT7ZdHYUmJoBoAIyzpew0DINl+iCZ6nTb/IioSxpJQAAA"
  },
  "gallery/detail-sweta-profile": {
    "src": "/images/gallery/detail-sweta-profile.jpg",
    "width": 580,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACQBACdASoQABcAPu1iqU2ppaOiMAgBMB2JYgCdMoCGACFU+y/pgqXOcjo9uoAA/jOwnhms1NizEiegInOADTKxMf2SydREcgDV6+es6vqasA5a3cHv5lvdfDOydBd9n8xz9EzVO1ZoidB2l2rkn8YBCoZjDX98xpd6G+mF2f1lqAfrsdgsU2xWKcxDgKk4wa604B6A5FGxT8GAAAA="
  },
  "gallery/detail-rahul-profile": {
    "src": "/images/gallery/detail-rahul-profile.jpg",
    "width": 560,
    "height": 800,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoQABcAPu1iqU2ppaOiMAgBMB2JZACsABh1shGjkEpZ49/e++wAAP7J3QRUiPr1cCq3feKHGg+9ucR2Nq1urXFggEBaBdXKLDQFDUlnG3crX5usc5HnYaEkMzFIkIxgjBTSEzDAdDj83A0zt+QIxbknnJ9tzejxnhZpaeHiydKo+6rXUHYwGw2r0gV0Z88IPxlPgAESodQTgAAA"
  }
} as const;

export type ImageId = keyof typeof imageManifest;
